name: Validate Steward Config
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/setup-action@v1
      with:
        apps: scala-steward
    - run: scala-steward validate-repo-config .github/.scala-steward.conf
